### PR TITLE
function and variable names are in backquotes

### LINKED ISSUE #173: Documentation:  Make sure all dataset and variable names on website are in backquotes
### Please select a category the issue is focused on?

_No response_

### Let us know where something needs a refresh or put your idea here!

At the moment, some dataset names and variable names are not in backquotes. This is against guidance. Review whole website to ensure this is fixed.

### PR DESCRIPTION
**Pull request by sonalijain17**
Closes #173 

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by manciniedoardo — CHANGES_REQUESTED** [review]
Hi @sonalijain17, thanks for working on this.

- The spellcheck is failing because when you (correctly) changed `ADIOP` to ADIOP in the standards vignette, the fact that the backquotes are gone - i.e. the this is now "text" and not "code" - means that our spelling checker is now analysing the word to see if it's a dictionary word, or if it's not. Given that "ADIOP" is not in the dictionary, the spellcheck flags it as a spelling error. But we know it's not a spelling error, so we want to add it to our own personal dictionary, which we can do by editing the file `inst/wordlist`. please could you go ahead and do that?
- The other check that is failing can be ignored.
- In `derive_var_studyeye()` reference page please could you ensure "SCTESTCD" is in backquotes too? 
- In derive_var_afeye please could you ensure "AFEYE" is always in backquotes?
- When on the "Reference" page on the website, I clicked on any of the example datasets, and I can still see datasets in backquotes under "Source" - see here for instance. Please could you edit that too? You can see this page is generated by the script `R/data.R`.
image

**Comment by sonalijain17** [comment]
Hi @manciniedoardo, thanks for reviewing and providing the comments. 
I have updated all of them. I have one suggestion that we keep dataset name in CAPS on the below page as well. Please let me know what you think and please guide me on where I can find the source script/document for this. 
image

**Comment by manciniedoardo** [comment]
> Hi @manciniedoardo, thanks for reviewing and providing the comments. I have updated all of them. I have one suggestion that we keep dataset name in CAPS on the below page as well. Please let me know what you think and please guide me on where I can find the source script/document for this page. image

I agree thanks. Please re-commit and we can see if the checks now pass 😄

**Comment by manciniedoardo** [comment]
Hi @sonalijain17 the man/Roxygen check is failing - please could you click on details and that should explain how to fix it thanks.

**Pull request merged**
